services:
  kafka:
    image: apache/kafka:3.8.0 # official Apache image, KRaft built-in
    container_name: kafka
    ports:
      - "9092:9092" # host-side access (your producer)
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: HOST://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: HOST:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: crypto
      POSTGRES_PASSWORD: crypto
      POSTGRES_DB: crypto
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U crypto -d crypto" ]
      interval: 5s
      timeout: 3s
      retries: 5
  kafka-ui:
    image: kafbat/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka

  airflow:
    image: apache/airflow:2.10.5 # pin a real 2.x tag — confirm it exists on hub.docker.com/r/apache/airflow/tags
    container_name: airflow
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8081:8080" # 8080 is taken by kafka-ui → UI lives at localhost:8081
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW_CONN_TRADES_PG: postgresql://crypto:crypto@postgres:5432/crypto
      _PIP_ADDITIONAL_REQUIREMENTS: apache-airflow-providers-postgres
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./sql:/opt/airflow/sql:ro
      - airflow_data:/opt/airflow
    command: standalone

volumes:
  pgdata:
  airflow_data:

